// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:data/cache/cache_hit.dart';
import 'package:data/cache/cache_system.dart';
import 'package:data/center/song_combination.dart';
import 'package:data/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AccountAdapter());
    registerAdapter(ArtistEntityAdapter());
    registerAdapter(BasicAlbumEntityAdapter());
    registerAdapter(CacheHitAdapter());
    registerAdapter(CacheInfoAdapter());
    registerAdapter(CityAdapter());
    registerAdapter(CloudMusicInfoAdapter());
    registerAdapter(GenderAdapter());
    registerAdapter(LoginResultAdapter());
    registerAdapter(MarkTypeAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(ProvinceAdapter());
    registerAdapter(SongCombinationAdapter());
    registerAdapter(SongEntityAdapter());
    registerAdapter(SongMatchTypeAdapter());
    registerAdapter(SongOriginBasicDataAdapter());
    registerAdapter(SongPrivilegeEntityAdapter());
    registerAdapter(SongPurchaseTypeAdapter());
    registerAdapter(SongQualityEntityAdapter());
    registerAdapter(SongQualityLevelAdapter());
    registerAdapter(SongSingTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AccountAdapter());
    registerAdapter(ArtistEntityAdapter());
    registerAdapter(BasicAlbumEntityAdapter());
    registerAdapter(CacheHitAdapter());
    registerAdapter(CacheInfoAdapter());
    registerAdapter(CityAdapter());
    registerAdapter(CloudMusicInfoAdapter());
    registerAdapter(GenderAdapter());
    registerAdapter(LoginResultAdapter());
    registerAdapter(MarkTypeAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(ProvinceAdapter());
    registerAdapter(SongCombinationAdapter());
    registerAdapter(SongEntityAdapter());
    registerAdapter(SongMatchTypeAdapter());
    registerAdapter(SongOriginBasicDataAdapter());
    registerAdapter(SongPrivilegeEntityAdapter());
    registerAdapter(SongPurchaseTypeAdapter());
    registerAdapter(SongQualityEntityAdapter());
    registerAdapter(SongQualityLevelAdapter());
    registerAdapter(SongSingTypeAdapter());
  }
}
