// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AtomicApi>>
abstract class AtomicApi implements RustOpaqueInterface {
  static AtomicBoolImpl createBool({required bool initial}) =>
      RustLib.instance.api.crateAtomicAtomicApiCreateBool(initial: initial);

  static AtomicCounter createCounter({required int initial}) =>
      RustLib.instance.api.crateAtomicAtomicApiCreateCounter(initial: initial);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AtomicBoolImpl>>
abstract class AtomicBoolImpl implements RustOpaqueInterface {
  bool compareAndSwap({required bool expected, required bool new_});

  bool get_();

  factory AtomicBoolImpl({required bool initial}) =>
      RustLib.instance.api.crateAtomicAtomicBoolImplNew(initial: initial);

  void set_({required bool value});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AtomicCounter>>
abstract class AtomicCounter implements RustOpaqueInterface {
  int add({required int value});

  int compareAndSwap({required int expected, required int new_});

  int decrement();

  int get_();

  int increment();

  factory AtomicCounter({required int initial}) =>
      RustLib.instance.api.crateAtomicAtomicCounterNew(initial: initial);

  void set_({required int new_});

  int sub({required int value});
}
