// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'atomic.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'smtc.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.10.0';

  @override
  int get rustContentHash => -1987862704;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'native',
        ioDirectory: 'native/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  AtomicBoolImpl crateAtomicAtomicApiCreateBool({required bool initial});

  AtomicCounter crateAtomicAtomicApiCreateCounter({required int initial});

  bool crateAtomicAtomicBoolImplCompareAndSwap({
    required AtomicBoolImpl that,
    required bool expected,
    required bool new_,
  });

  bool crateAtomicAtomicBoolImplGet({required AtomicBoolImpl that});

  AtomicBoolImpl crateAtomicAtomicBoolImplNew({required bool initial});

  void crateAtomicAtomicBoolImplSet({
    required AtomicBoolImpl that,
    required bool value,
  });

  int crateAtomicAtomicCounterAdd({
    required AtomicCounter that,
    required int value,
  });

  int crateAtomicAtomicCounterCompareAndSwap({
    required AtomicCounter that,
    required int expected,
    required int new_,
  });

  int crateAtomicAtomicCounterDecrement({required AtomicCounter that});

  int crateAtomicAtomicCounterGet({required AtomicCounter that});

  int crateAtomicAtomicCounterIncrement({required AtomicCounter that});

  AtomicCounter crateAtomicAtomicCounterNew({required int initial});

  void crateAtomicAtomicCounterSet({
    required AtomicCounter that,
    required int new_,
  });

  int crateAtomicAtomicCounterSub({
    required AtomicCounter that,
    required int value,
  });

  void crateSmtcSmtcFlutterClose({required SmtcFlutter that});

  SmtcFlutter crateSmtcSmtcFlutterNew();

  Stream<int> crateSmtcSmtcFlutterSubscribeToControlEvents({
    required SmtcFlutter that,
  });

  void crateSmtcSmtcFlutterUpdateDisplay({
    required SmtcFlutter that,
    required String title,
    required String artist,
    required String album,
    String? path,
  });

  void crateSmtcSmtcFlutterUpdateState({
    required SmtcFlutter that,
    required SMTCState state,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AtomicApi;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AtomicApi;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AtomicApiPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AtomicBoolImpl;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AtomicBoolImpl;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AtomicBoolImplPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AtomicCounter;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AtomicCounter;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AtomicCounterPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SmtcFlutter;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SmtcFlutter;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SmtcFlutterPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  AtomicBoolImpl crateAtomicAtomicApiCreateBool({required bool initial}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(initial, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl,
          decodeErrorData: null,
        ),
        constMeta: kCrateAtomicAtomicApiCreateBoolConstMeta,
        argValues: [initial],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAtomicAtomicApiCreateBoolConstMeta =>
      const TaskConstMeta(
        debugName: "AtomicApi_create_bool",
        argNames: ["initial"],
      );

  @override
  AtomicCounter crateAtomicAtomicApiCreateCounter({required int initial}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(initial, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter,
          decodeErrorData: null,
        ),
        constMeta: kCrateAtomicAtomicApiCreateCounterConstMeta,
        argValues: [initial],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAtomicAtomicApiCreateCounterConstMeta =>
      const TaskConstMeta(
        debugName: "AtomicApi_create_counter",
        argNames: ["initial"],
      );

  @override
  bool crateAtomicAtomicBoolImplCompareAndSwap({
    required AtomicBoolImpl that,
    required bool expected,
    required bool new_,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl(
            that,
            serializer,
          );
          sse_encode_bool(expected, serializer);
          sse_encode_bool(new_, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateAtomicAtomicBoolImplCompareAndSwapConstMeta,
        argValues: [that, expected, new_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAtomicAtomicBoolImplCompareAndSwapConstMeta =>
      const TaskConstMeta(
        debugName: "AtomicBoolImpl_compare_and_swap",
        argNames: ["that", "expected", "new_"],
      );

  @override
  bool crateAtomicAtomicBoolImplGet({required AtomicBoolImpl that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateAtomicAtomicBoolImplGetConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAtomicAtomicBoolImplGetConstMeta =>
      const TaskConstMeta(debugName: "AtomicBoolImpl_get", argNames: ["that"]);

  @override
  AtomicBoolImpl crateAtomicAtomicBoolImplNew({required bool initial}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(initial, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl,
          decodeErrorData: null,
        ),
        constMeta: kCrateAtomicAtomicBoolImplNewConstMeta,
        argValues: [initial],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAtomicAtomicBoolImplNewConstMeta =>
      const TaskConstMeta(
        debugName: "AtomicBoolImpl_new",
        argNames: ["initial"],
      );

  @override
  void crateAtomicAtomicBoolImplSet({
    required AtomicBoolImpl that,
    required bool value,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl(
            that,
            serializer,
          );
          sse_encode_bool(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateAtomicAtomicBoolImplSetConstMeta,
        argValues: [that, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAtomicAtomicBoolImplSetConstMeta =>
      const TaskConstMeta(
        debugName: "AtomicBoolImpl_set",
        argNames: ["that", "value"],
      );

  @override
  int crateAtomicAtomicCounterAdd({
    required AtomicCounter that,
    required int value,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
            that,
            serializer,
          );
          sse_encode_i_32(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateAtomicAtomicCounterAddConstMeta,
        argValues: [that, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAtomicAtomicCounterAddConstMeta =>
      const TaskConstMeta(
        debugName: "AtomicCounter_add",
        argNames: ["that", "value"],
      );

  @override
  int crateAtomicAtomicCounterCompareAndSwap({
    required AtomicCounter that,
    required int expected,
    required int new_,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
            that,
            serializer,
          );
          sse_encode_i_32(expected, serializer);
          sse_encode_i_32(new_, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateAtomicAtomicCounterCompareAndSwapConstMeta,
        argValues: [that, expected, new_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAtomicAtomicCounterCompareAndSwapConstMeta =>
      const TaskConstMeta(
        debugName: "AtomicCounter_compare_and_swap",
        argNames: ["that", "expected", "new_"],
      );

  @override
  int crateAtomicAtomicCounterDecrement({required AtomicCounter that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateAtomicAtomicCounterDecrementConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAtomicAtomicCounterDecrementConstMeta =>
      const TaskConstMeta(
        debugName: "AtomicCounter_decrement",
        argNames: ["that"],
      );

  @override
  int crateAtomicAtomicCounterGet({required AtomicCounter that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateAtomicAtomicCounterGetConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAtomicAtomicCounterGetConstMeta =>
      const TaskConstMeta(debugName: "AtomicCounter_get", argNames: ["that"]);

  @override
  int crateAtomicAtomicCounterIncrement({required AtomicCounter that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateAtomicAtomicCounterIncrementConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAtomicAtomicCounterIncrementConstMeta =>
      const TaskConstMeta(
        debugName: "AtomicCounter_increment",
        argNames: ["that"],
      );

  @override
  AtomicCounter crateAtomicAtomicCounterNew({required int initial}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(initial, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter,
          decodeErrorData: null,
        ),
        constMeta: kCrateAtomicAtomicCounterNewConstMeta,
        argValues: [initial],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAtomicAtomicCounterNewConstMeta =>
      const TaskConstMeta(
        debugName: "AtomicCounter_new",
        argNames: ["initial"],
      );

  @override
  void crateAtomicAtomicCounterSet({
    required AtomicCounter that,
    required int new_,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
            that,
            serializer,
          );
          sse_encode_i_32(new_, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateAtomicAtomicCounterSetConstMeta,
        argValues: [that, new_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAtomicAtomicCounterSetConstMeta =>
      const TaskConstMeta(
        debugName: "AtomicCounter_set",
        argNames: ["that", "new_"],
      );

  @override
  int crateAtomicAtomicCounterSub({
    required AtomicCounter that,
    required int value,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
            that,
            serializer,
          );
          sse_encode_i_32(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateAtomicAtomicCounterSubConstMeta,
        argValues: [that, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAtomicAtomicCounterSubConstMeta =>
      const TaskConstMeta(
        debugName: "AtomicCounter_sub",
        argNames: ["that", "value"],
      );

  @override
  void crateSmtcSmtcFlutterClose({required SmtcFlutter that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateSmtcSmtcFlutterCloseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSmtcSmtcFlutterCloseConstMeta =>
      const TaskConstMeta(debugName: "SmtcFlutter_close", argNames: ["that"]);

  @override
  SmtcFlutter crateSmtcSmtcFlutterNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter,
          decodeErrorData: null,
        ),
        constMeta: kCrateSmtcSmtcFlutterNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSmtcSmtcFlutterNewConstMeta =>
      const TaskConstMeta(debugName: "SmtcFlutter_new", argNames: []);

  @override
  Stream<int> crateSmtcSmtcFlutterSubscribeToControlEvents({
    required SmtcFlutter that,
  }) {
    final sink = RustStreamSink<int>();
    handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter(
            that,
            serializer,
          );
          sse_encode_StreamSink_i_32_Sse(sink, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateSmtcSmtcFlutterSubscribeToControlEventsConstMeta,
        argValues: [that, sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateSmtcSmtcFlutterSubscribeToControlEventsConstMeta =>
      const TaskConstMeta(
        debugName: "SmtcFlutter_subscribe_to_control_events",
        argNames: ["that", "sink"],
      );

  @override
  void crateSmtcSmtcFlutterUpdateDisplay({
    required SmtcFlutter that,
    required String title,
    required String artist,
    required String album,
    String? path,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter(
            that,
            serializer,
          );
          sse_encode_String(title, serializer);
          sse_encode_String(artist, serializer);
          sse_encode_String(album, serializer);
          sse_encode_opt_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateSmtcSmtcFlutterUpdateDisplayConstMeta,
        argValues: [that, title, artist, album, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSmtcSmtcFlutterUpdateDisplayConstMeta =>
      const TaskConstMeta(
        debugName: "SmtcFlutter_update_display",
        argNames: ["that", "title", "artist", "album", "path"],
      );

  @override
  void crateSmtcSmtcFlutterUpdateState({
    required SmtcFlutter that,
    required SMTCState state,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter(
            that,
            serializer,
          );
          sse_encode_smtc_state(state, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateSmtcSmtcFlutterUpdateStateConstMeta,
        argValues: [that, state],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSmtcSmtcFlutterUpdateStateConstMeta =>
      const TaskConstMeta(
        debugName: "SmtcFlutter_update_state",
        argNames: ["that", "state"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AtomicApi =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicApi;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AtomicApi =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicApi;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AtomicBoolImpl =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AtomicBoolImpl =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AtomicCounter =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AtomicCounter =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SmtcFlutter =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SmtcFlutter =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  AtomicApi
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AtomicApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AtomicBoolImpl
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AtomicBoolImplImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AtomicCounter
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AtomicCounterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SmtcFlutter
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SmtcFlutterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AtomicBoolImpl
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AtomicBoolImplImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AtomicCounter
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AtomicCounterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SmtcFlutter
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SmtcFlutterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AtomicApi
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AtomicApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AtomicBoolImpl
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AtomicBoolImplImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AtomicCounter
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AtomicCounterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SmtcFlutter
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SmtcFlutterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<int> dco_decode_StreamSink_i_32_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  SMTCState dco_decode_smtc_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SMTCState.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  AtomicApi
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AtomicApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AtomicBoolImpl
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AtomicBoolImplImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AtomicCounter
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AtomicCounterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SmtcFlutter
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SmtcFlutterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AtomicBoolImpl
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AtomicBoolImplImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AtomicCounter
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AtomicCounterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SmtcFlutter
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SmtcFlutterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AtomicApi
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AtomicApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AtomicBoolImpl
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AtomicBoolImplImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AtomicCounter
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AtomicCounterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SmtcFlutter
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SmtcFlutterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<int> sse_decode_StreamSink_i_32_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SMTCState sse_decode_smtc_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SMTCState.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicApi(
    AtomicApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AtomicApiImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl(
    AtomicBoolImpl self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AtomicBoolImplImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
    AtomicCounter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AtomicCounterImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter(
    SmtcFlutter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SmtcFlutterImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl(
    AtomicBoolImpl self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AtomicBoolImplImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
    AtomicCounter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AtomicCounterImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter(
    SmtcFlutter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SmtcFlutterImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicApi(
    AtomicApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AtomicApiImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicBoolImpl(
    AtomicBoolImpl self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AtomicBoolImplImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAtomicCounter(
    AtomicCounter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AtomicCounterImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSmtcFlutter(
    SmtcFlutter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SmtcFlutterImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_i_32_Sse(
    RustStreamSink<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_smtc_state(SMTCState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class AtomicApiImpl extends RustOpaque implements AtomicApi {
  // Not to be used by end users
  AtomicApiImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AtomicApiImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AtomicApi,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AtomicApi,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AtomicApiPtr,
  );
}

@sealed
class AtomicBoolImplImpl extends RustOpaque implements AtomicBoolImpl {
  // Not to be used by end users
  AtomicBoolImplImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AtomicBoolImplImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AtomicBoolImpl,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AtomicBoolImpl,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AtomicBoolImplPtr,
  );

  bool compareAndSwap({required bool expected, required bool new_}) =>
      RustLib.instance.api.crateAtomicAtomicBoolImplCompareAndSwap(
        that: this,
        expected: expected,
        new_: new_,
      );

  bool get_() => RustLib.instance.api.crateAtomicAtomicBoolImplGet(that: this);

  void set_({required bool value}) => RustLib.instance.api
      .crateAtomicAtomicBoolImplSet(that: this, value: value);
}

@sealed
class AtomicCounterImpl extends RustOpaque implements AtomicCounter {
  // Not to be used by end users
  AtomicCounterImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AtomicCounterImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AtomicCounter,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AtomicCounter,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AtomicCounterPtr,
  );

  int add({required int value}) => RustLib.instance.api
      .crateAtomicAtomicCounterAdd(that: this, value: value);

  int compareAndSwap({required int expected, required int new_}) =>
      RustLib.instance.api.crateAtomicAtomicCounterCompareAndSwap(
        that: this,
        expected: expected,
        new_: new_,
      );

  int decrement() =>
      RustLib.instance.api.crateAtomicAtomicCounterDecrement(that: this);

  int get_() => RustLib.instance.api.crateAtomicAtomicCounterGet(that: this);

  int increment() =>
      RustLib.instance.api.crateAtomicAtomicCounterIncrement(that: this);

  void set_({required int new_}) =>
      RustLib.instance.api.crateAtomicAtomicCounterSet(that: this, new_: new_);

  int sub({required int value}) => RustLib.instance.api
      .crateAtomicAtomicCounterSub(that: this, value: value);
}

@sealed
class SmtcFlutterImpl extends RustOpaque implements SmtcFlutter {
  // Not to be used by end users
  SmtcFlutterImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SmtcFlutterImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SmtcFlutter,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SmtcFlutter,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SmtcFlutterPtr,
  );

  /// Apis for Flutter
  void close() => RustLib.instance.api.crateSmtcSmtcFlutterClose(that: this);

  /// Apis for Flutter
  Stream<int> subscribeToControlEvents() => RustLib.instance.api
      .crateSmtcSmtcFlutterSubscribeToControlEvents(that: this);

  /// Apis for Flutter
  void updateDisplay({
    required String title,
    required String artist,
    required String album,
    String? path,
  }) => RustLib.instance.api.crateSmtcSmtcFlutterUpdateDisplay(
    that: this,
    title: title,
    artist: artist,
    album: album,
    path: path,
  );

  /// Apis for Flutter
  void updateState({required SMTCState state}) => RustLib.instance.api
      .crateSmtcSmtcFlutterUpdateState(that: this, state: state);
}
