// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_init_controls`, `_new`, `_update_display`, `_update_state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SMTCControlEvent`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SmtcFlutter>>
abstract class SmtcFlutter implements RustOpaqueInterface {
  /// Apis for Flutter
  void close();

  /// Apis for Flutter
  factory SmtcFlutter() => RustLib.instance.api.crateSmtcSmtcFlutterNew();

  /// Apis for Flutter
  Stream<int> subscribeToControlEvents();

  /// Apis for Flutter
  void updateDisplay({
    required String title,
    required String artist,
    required String album,
    String? path,
  });

  /// Apis for Flutter
  void updateState({required SMTCState state});
}

enum SMTCState { paused, playing }
